Fix Circle CI shell-linting job
Since it's currently failing with:

```
apk add shfmt --repository=http://dl-3.alpinelinux.org/alpine/edge/community

fetch http://dl-3.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-3.alpinelinux.org/alpine/edge/community: UNTRUSTED signature
WARNING: Ignoring APKINDEX.286cd1a4.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  shfmt (missing):
    required by: world[shfmt]

Exited with code exit status 1
```

eg:
https://app.circleci.com/pipelines/github/heroku/buildpacks-jvm/1132/workflows/2c116abf-58a6-4bd7-9f48-70c6de8c27e0/jobs/14280